version: '3.9'

services:
  bot:
    container_name: bot
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - "8011:8011"
    command: scripts/web/startup.sh -m -l
    restart: on-failure
    env_file:
      - ./conf/.env
    volumes:
      - .:/code
    networks:
      - vd_network
networks:
  vd_network:
    external: True